---
- name: "Apache setup"
  hosts: lamp_servers
  become: true
  vars_files:
    - ../group_vars/all/main.yml
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
  tasks:
    - name: "Install Apache"
      apt:
        name: apache2
        state: present
      notify: restart apache

    - name: "Install apache modules"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2-utils
      notify: restart apache

    - name: "Enable apache modules"
      command: "a2enmod {{ item }}"
      args:
        creates: "/etc/apache2/mods-enabled/{{ item }}.load"
      loop: "{{ apache_modules }}"
      notify: restart apache

    - name: "Create document root"
      file:
        path: "{{ document_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: "Deploy virtualhost template"
      template:
        src: ../templates/vhost.conf.j2
        dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
        owner: root
        group: root
        mode: '0644'
      notify: restart apache

    - name: "Enable site"
      command: "a2ensite {{ domain_name }}.conf"
      args:
        creates: "/etc/apache2/sites-enabled/{{ domain_name }}.conf"
      notify: restart apache

    - name: "Disable default site"
      command: "a2dissite 000-default.conf"
      args:
        removes: "/etc/apache2/sites-enabled/000-default.conf"
      failed_when: false
      notify: restart apache
