---
- name: "MySQL setup"
  hosts: lamp_servers
  become: true

  vars_prompt:
    - name: mysql_root_password
      prompt: "Enter MySQL root password"
      private: yes

    - name: mysql_app_password
      prompt: "Enter application DB password"
      private: yes

  tasks:
    - name: "Install MySQL server and python libs"
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present
        update_cache: yes

    - name: "Ensure MySQL service is started and enabled"
      service:
        name: mysql
        state: started
        enabled: yes

    - name: "Allow root login with password (disable unix_socket auth)"
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: '*.*:ALL,GRANT'
        state: present

    - name: "Create application database"
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: "Create application DB user"
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_app_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
